#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 同步源码

on:
  # push:
  #   branches: 
  #     - master
  schedule:
    - cron: 0 0/4 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: 校验本地文件
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: 设置提交者
      run : |
        git config --global user.email "254975828@qq.com"
        git config --global user.name "lico"

    - name: 拉取
      run: git pull https://github.com/coolsnowwolf/lede.git --no-edit

    - name: 推送
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
        
