#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 云编译

on:
  push:
    branches: 
      - master
    paths:
      - 'buildInfo.yml'
  # pull_request:
  #   types: [synchronize]
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /etc/mysql /etc/php
          sudo swapoff /swapfile
          sudo rm -f /swapfile
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      
      # - name: 构建自定义文件结构
      #   run: |
      #     cd package
      #     mkdir openwrt-packages
      #     cd openwrt-packages
      #     git clone https://github.com/rosywrt/luci-theme-rosy.git

      - name: 构建程序包
        run: |
          ./scripts/feeds clean
          ./scripts/feeds update -a
          rm -rf feeds/lienol/package/v2ray
          rm -rf feeds/lienol/package/trojan
          rm -rf feeds/lienol/package/openssl1.1
          rm -rf feeds/lienol/package/ipt2socks
          rm -rf feeds/lienol/package/shadowsocksr-libev
          rm -rf feeds/lienol/package/pdnsd-alt
          rm -rf feeds/lienol/lienol/luci-app-kodexplorer
          rm -rf package/lean/kcptun
          rm -rf package/lean/verysync
          rm -rf package/lean/luci-app-pppoe-relay
          rm -rf package/lean/luci-app-pptp-server
          rm -rf package/lean/luci-app-v2ray-server
          rm -rf package/lean/luci-app-verysync
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      
      - name: 自定义文件
        run: |
          rm -f ./.config*
          cp ./makeconfig.d/x86_64.config ./.config
          make defconfig

      
      - name: 下载编译所需源码
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;


      - name: 进行固件编译
        run: DEBIAN_FRONTEND=noninteractive make -j$(nproc) V=s


      - name: 清理不必要的文件
        run: |
          find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
          find ./bin/targets/ -name "*rootfs*img*" | xargs rm -rf {}


      - name : 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
